// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dccrnubcfpcwugjontnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjY3JudWJjZnBjd3Vnam9udG5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NTExNDUsImV4cCI6MjA3MzUyNzE0NX0.Q41Q7HzAGZqSnfmDgrT96YtNCJvrSn3_tTJdLbldI6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});